port: 8080
imageFolder: ./images/
grpcEndPoint: flair-engine-grpc:6565
mailService:
    serive: sendgrid
    sender: admin-vizcentric@gmail.com
    testUser: admin@vizcentric.com
    host: smtp.sendgrid.net
    port: 587
    auth :
      user: <key name>
      pass: <password>
